### ISSUE TITLE
update example in codesandbox

### ISSUE THREAD

**Issue by ahmadtlz** [react-spring/react-use-gesture#193] opened 2020-07-30 04:35 UTC
i wanna use this example
https://codesandbox.io/embed/zrj66y8714
or other example that related to react-use-gesture but idk how use it

**Comment by dbismut** [comment] 2020-07-31 08:33
@ahmadtlz there https://codesandbox.io/s/cold-violet-b9rgd
Closing since since this is a question (ie not a bug), but feel free to comment further should you want more explanation.

**Closed by dbismut** 2020-07-31 08:33 UTC
