### ISSUE TITLE
 Fetch data asynchronously in function component with useGesture

### ISSUE THREAD

**Issue by pennjlin** [react-spring/react-use-gesture#142] opened 2020-03-11 04:01 UTC
@dbismut How should I handle dynamically loaded data with `useSprings()` + `useGesture()`? I was using `react-with-gesture` previously, but even after I updated it to latest `react-use-gesture`, the same issue persists. What'd be the correct way to support async/await data fetching with `react-springs`?

_Originally posted by @pennjlin in https://github.com/react-spring/react-use-gesture/issues/141#issuecomment-597383811_

**Comment by dbismut** [comment] 2020-03-11 06:14
Duplicate of #141

**Closed by dbismut** 2020-03-11 06:14 UTC
